### ISSUE TITLE
Can we use HttpClient Outgoing Middleware with this?

### ISSUE THREAD

**Issue by VictorioBerra** [ExusAltimus/AlphaVantage.NET#1]
I want to use [outgoing middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2)

It would be nice to be able to provide my own HttpClient and attach my own middleware.

**Comment by ExusAltimus** [comment]
Yep! I tried my best to design every part to be replaceable, this project is still very bare bones so be wary of bugs. 
To implement your own HttpClient create a class that implements IApiWebClient
(See [ApiWebClient.cs](https://github.com/ExusAltimus/AlphaVantage.NET/blob/master/Exus.AlphaVantage/WebClient/ApiWebClient.cs) for default implementation)

Then add your implementation to your DI container.
`services.AddTransient<IApiWebClient, MyApiHttpClient>();
`

If you are not using a DI framework then you can pass your implementation using 
`public ApiQuerier(IApiWebClient webClient, IOptions<ApiQuerierSettings> options)`
[ApiQuerier.cs](https://github.com/ExusAltimus/AlphaVantage.NET/blob/master/Exus.AlphaVantage/Querier/ApiQuerier.cs)
