### ISSUE TITLE
NuGet Package? Link to package?

### ISSUE THREAD

**Issue by VictorioBerra** [ExusAltimus/AlphaVantage.NET#2]
If there is a package, can we get a link to it on the README?

👉  `dotnet package add ExusAltimus.AlphaVantage.NET`

**Comment by ExusAltimus** [comment]
Currently no nuget package, I’ll update it later today once I’m off of work

**Comment by ExusAltimus** [comment]
https://www.nuget.org/packages/Exus.AlphaVantage.Core/
